### ISSUE TITLE
Problem with joint distribution and kde 

### ISSUE THREAD

**Issue by chomikzimon** [jonathf/chaospy#117]
Hi!

Thank you for your code! I use it a lot!

I have a problem with generating samples from a joint probability distribution which contains kdedist.
I receive `AttributeError: 'Graph' object has no attribute 'K'`.

Please see the code below.

**Comment by chomikzimon** [comment]
Hi!

Thank you for your code. I use it a lot!

I have a problem with generating samples from a joint probability distribution which contains kdedist.
The following works:

`from chaospy import SampleDist`
`KDEDist = SampleDist(array([0, 1, 1, 1, 1, 1, 1, 2]))`
`KDEDist.sample(1)`

But it breaks if I generate a joint distribution:
`from chaospy import J, Uniform`
`Distribution = J(KDEDist, Uniform(0, 1))`
`Distribution.sample(1)`

Is there an attribute missing in SampleDist object?

Thank you for your help!
Maggie

**Comment by flo2k** [comment]
Dear Maggie,

I can reproduce your error.

@jonathf Could the error be caused, because in the `class kdedist(Dist)` I implemented the `sample()` method by myself. This allows one to sample from a 1D kdedist distribution. Do you think that it is possible to use the `sample()` method of a distribution if it is implemented even in a joined dist and otherwise the way you do it now?

Best,

Florian

**Comment by jonathf** [comment]
So there is a bigger overhanging topic here that has a few components to it, so bare with me.

In the current version of chaospy `sample` is a frontend method meant to only be used by the user. By putting it into a distribution construct, it never get called. With nested distribution, samples are instead mapped using the inverse Rosenblatt transform to the space of interest. Less efficient, but more generalizable. The internal machinery though sees that the component is missing an inverse function, so it tries to estimate it using pdf and cdf. It fails since the kernel is a lot more fragile than I'd like.

The good news is that I've already replaced the current machinger with a new backend that isn't as fragile. It can be found on the branch `clean_dist` and can be used right away. Since it is kind of big change, I have been reluctant to make the leap and merge it into the main branch. Perhaps this is the point to make the leap.

I've tried out the SampleDist with the new backend and the machinery is doing what it is suppose to be doing, which is the same approximation as above, but without the errors.

Unfortunately, the approx method fails to converge because of a problematic features in `scipy.stats.gaussian_kde`: The upper bound of the CDF converges unreasonably slow towards 1. This causes the method to quite slow and inaccurate when performing sample generation.

There is, however, a simple fix:
If we replace `scipy.stats.gaussian_kde` with `statsmodels.nonparametric.kde.KDEUnivariate`, we should get the support we need to get accuracy up. The only major caveat being that chaospy would have to add `statsmodels` to it's dependency list. I don't have a problem with that.

Implementation should be quite quick, but before I start: @flo2k, what is your thoughts on this switch? Any reason not to switch to the statsmodel version of KDE over the scipy variant?

**Comment by flo2k** [comment]
@jonathf as far as I could see: it is no problem for me to add this new dependency. 

Maybe it's a good idea to switch to `statsmodel` anyway, because it might also support multivariate KDEs much easier than `scipy`.

If you have something, I can test it with my existing tests, to see if I get nearly comparable results.

**Comment by jonathf** [comment]
@flo2k,

I just looked at the internal implementation of `KDEUnivariate` now, and got quite underwhelmed. The cdf and icdf there does not align up, making it essentially useless as a Rosenblatt transformation. The cdf is done using the kernel, but the icdf is done using `scipy.stats.mstats.mquartiles`.

`KDEMultivariate` does not support inverse transformations, and is discussed at bit in #83. The results were that I could get it to work on multivariate problems, but the accuracy wasn't very impressive. I might have a second look at that aspect again soon. It would be a really cool feature.

As for the current implementation, thought wise it looks like we might be able to save it if we can resolve an internal contradiction:

The way you have implemented `_bnd`, you set the theoretical upper and lower bounds to `lo` and `up`. The model assumes that `dist.cdf([lo, up]) == (0, 1)`. The problem arises when this does not hold. In fact the value here the CDF reaches 1, is way too high for it to be practical. (Looks like `lo` is fine for the example here.)

I've added a small enhancement such that `dist.cdf([lo, up]) == (0, 1)` holds. If we want the PDF to be non-zero outside `(samples.min(), samples.max())`, we might want to think about adjusting default `(lo, up)` to be wider.

Please take a look. I've made an update to `clean_dist` branch and the file `src/chaospy/distributions/collection/sample_dist.py`.

**Comment by flo2k** [comment]
With the latest change in https://github.com/jonathf/chaospy/pull/80 I think everything works as expected.

**Comment by chomikzimon** [comment]
Hi @flo2k , @jonathf,

Thank you for taking the time to look at this issue. Would you suggest using the new implementation in
`src/chaospy/distributions/collection/sample_dist.py` ?

Best wishes,
Maggie

**Comment by jonathf** [comment]
No problem.

Yes, for the time being, I suggest using it. I will merge the branch over to main branch over Christmas. I just want to make sure there aren't any more glaring bugs luring before I do.
