### ISSUE TITLE
Results comparison between UQlab and Chaospy

### ISSUE THREAD

**Issue by Plancalkuele** [jonathf/chaospy#120]
Hi there,
I'm trying to find out what the difference between my UQlab implementation and my Chaospy implementation is and why I receive better results with UQlab.

The manual of UQlab for PCE can be found here: [UQLab User Manual](https://www.uqlab.com/userguidepce)

I have 15 inputs to my model being normally distributed and receive the following surrogate with UQLab:

```
polynomial degree/order: 3
modified leave-one-out error: 0.1538
R^2: 0.9148
MSE: 2.3447e-09
Number of non-zero coefficients: 89
```

When turning off the hybrid LARS (the first coefficient is set to the mean of the experimental design) the fit gets worse:

```
polynomial degree/order: 3
modified leave-one-out error: 0.0052
R^2: 0.8832
MSE: 3.6880e-09
Number of non-zero coefficients: 89
```

Here the main steps I do in Chaospy:
```
order = 3
orth_polynomials = cp.orth_ttr(order = order, dist = distribution, retall=False)
lassolarscv = LassoLarsCV(fit_intercept=False)
cp.fit_regression(orth_polynomials, X_train.T, Y_train, rule=lassolarscv)
```

I also tried to use sklearn.linear_model.Lars and fixed n_nonzero_coefs to 89 since UQLab generates a polynomial with 89 non-zero coefficients. But had no success with obtaining same results.

Here are the options I set in UQLab:
```
MetaOpts.Method = 'LARS';
MetaOpts.LARS.HybridLars = 0;
MetaOpts.OLS.ModifiedLOO = 0;
```

I would like to find out why exactly UQLab performs better so that I can get a equivalent fit with the Chaospy implementation.

I think it depends on the adaptive algorithm UQLab uses. But I'm not too sure and any comments, suggestions and help would be very much appreciated.

Here is the paper on the adaptive algorithm which UQLab generates the polynomials with:
https://doi.org/10.1016/j.probengmech.2009.10.003

**Comment by jonathf** [comment]
I've skimmed through the paper and it looks like a very interesting approach. My first thought was clearly the same as yours that you might be able to get close to the same behavior by applying a rule from `sklearn` that could fit. Unfortunately, the question if the rule is correct or not is an issue with `chaospy` but between `UQLab` and `sklearn`. This is not the right forum for that, and I don't know enough about either.

That being said, putting my academic hat on for a moment instead of the maintainer hat, I would say that replicating the pseudo-code in appendix B looks surprisingly simple to replicate.

I suggestion you download the `chaospy` repository and take a look at the internals of the function `caospy.regression.fit_regression`.
Also have a look at `chaospy.bertran.bindex`. It will give you the `alpha`-set from the paper. (Just make sure the flags `rule, cross_truncation` is the same for both `bindex` and `orth_ttr`). Orthogonal polynomials returned bu `orth_ttr` are numpy slicable, so I don't imagine `chaospy` being the bottleneck, and it wouldn't be too complicated implement the features in this paper.

And if you choose to go down that route, feel free to ask questions along the way here, and I will help where I can on the `chaospy` side of things.

**Comment by Plancalkuele** [comment]
Thanks so much for the help! I will let you know how I progress and, if successful at some point, share the code with you. Cheers!
