### ISSUE TITLE
Correct usage of the Pearson’s Correlation Corr.

### ISSUE THREAD

**Issue by ar-valdez** [jonathf/chaospy#138]
Dear Jonathf,

Hello I am trying to perform sensitivity analysis between the inputs and outputs of the model. I want to understand how a certain QoI changes assuming changes on the inputs.

Once defined the polynomial fitting I am trying to evaluate the correlation, between the fitted polynomial and the distribution that was used for the polynomial fitting. For example see the following excerpt  of a code:
`true_sample = np.array(true_sample)`

`poly_expansion = cp.orth_ttr(deg, dist)`

`poly = cp.fit_regression(poly_expansion, true_sample.T, sample)`

Untill here everything is ok... The next step produces an execution error:

`corr = cp.Corr([poly, dist])`

The example available in the [example](https://chaospy.readthedocs.io/en/development/descriptives.html#pearson-s-correlation-corr) I tried to adapt it to my needs but still not able....

**Comment by jonathf** [comment]
I think you are reading the function signature incorrectly. The correct format for simple correlation is:
```python
corr = cp.Corr(poly, dist)
```

Does this cover your use case, or are you looking into doing something more fancy?

**Comment by nguyenhoaiThanhbk2811** [comment]
Dear ar-valdez,
I am working gPC. Could you contact with me via email. "hoaithanhbk281113@gmail.com". I am sorry If I have bothered you.
Thank you

**Comment by ar-valdez** [comment]
> I think you are reading the function signature incorrectly. The correct format for simple correlation is:
> 
> ```python
> corr = cp.Corr(poly, dist)
> ```
> 
> Does this cover your use case, or are you looking into doing something more fancy?

Dear Jonathan f this was my first option. But it didn't work. In the documentation you said that poly is an array containing the polynomial and the distribution. That's why I decided to ask this issue

**Comment by jonathf** [comment]
The signature allows for passing poly or a dist. If a dist is provided, this would be a shortcut for doing `cp.Corr(cp.variable(1), dist)`, i.e. taking the metric against the distribution itself.

In the context of polynomial chaos expansion, it often makes sense of thinking probability distributions as weighted Hilbert spaces. When taking e.g. `E[X]` this implies both the expected value of the function `f(X)=X`, but also that the expected value should be taken in the weighted space where `p_X(x)` is the weight function.

In `chaospy` both function (in the form of a polynomial) and the weighted space (in the form of a distribution) has to be provided. E.g. `E[X]` is formulated as `cp.E(poly, dist)`, as it makes no implicit assumption about the connection between the function and the Hilbert space.

In the case of `cp.Corr`, the operation requires at least three components: two functions and one distribution. This is because correlation is a compare between two functions. When you provide a poly, like you are doing, this only makes sense if the length of said polynomial is longer than one. This depends on the shape of your `true_samples`.

My guess here is that your `poly` is scalar and therefore does not cover your use case. But I am guessing. I don't know your use case, so to answer your question: I need to know more about the what you expect to do.

**Comment by ar-valdez** [comment]
I understand, the shape of `true_samples` is bugging my implementation. will check that and give the feedback.

Thanks

**Comment by jonathf** [comment]
My apologies, I didn't see the edit you made to your comment before now.

Yes, `poly.shape == ()` implies scalar polynomial. All Operators `E, Std, Sens_m, Sens_m2, Sens_t` only requires scalar inputs. `Corr` together with `Cov` requires at least two components to make sense.

I've added a default to master such that scalar `Corr(dist) == [[1.]]` and `Cov(dist) == [[Var(dist)]]`. This should be consistent behavior with theory.

I am closing the issue here. If you have further questions feel free to reopen.
