### ISSUE TITLE
non-intrusive polynomial chaos expansion method

### ISSUE THREAD

**Issue by daxterss** [jonathf/chaospy#204]
HI there,

First of all, thank you very much for developing and maintaining chaospy! I am starting with PCE and it is very helpful!

I would like to use NIPCE for CFD with UQ and optimisation design purposes. My understanding is that I need the Pseudo-spectral Projection method. I will have 3-5 uncertainty parameters, which suggest that I should be using the Sparse method (is that right?). 

My idea is to get the "absissas" which then I will use for the perturbation in my CFD models using the following lines ( this is an example for 3 uncertainty parameters):

distribution = cp.J(cp.Uniform(1, 2),cp.Uniform(0.1, 0.2), cp.Uniform(0,1))
polynomial_expansion = cp.orth_ttr(order1, distribution)
absissas, weights = cp.generate_quadrature(order=order2, dist=distribution,sparse=True)

My first issue here is how to determine "order1" and "order2". I was thinking to have a baseline case run a MonteCarlo simulation and calculate the mean, std and histogram... Then, workout which value of order1 and order2 match them and use those settings for my optimisation studies... I guess that those settings dependent on the application so it is a "safe" manner to determine these hyperparameters. Would you use that approach? or can you recommend other?

Once I am happy with the hyperpamaters, I can fit the quadrature (foo_approx) and calculate the mean or std. To plot the PDF, I think that I should use the following lines:

qoi_dist =cp.QoI_Dist(foo_approx,distribution)
pdf_samples = qoi_dist[0].pdf(dist_sampling_values)

Nevertheless, I did very quick checks of plotting the PDF for the easy example of your tutorial from the documentation and realized of few things: (1) the shape changes a lot with the order of quadrature (maybe because it is very unstable?), (2) the values of PDF can be above 1 (is that really possible?)

Thank you very much and looking forward to hearing from you
Sorry for so many questions but

**Comment by jonathf** [comment]
There is no rule that require you to use PSP. You can use regression based method just as well.

As for sparse, that is a computational budget question. If you can afford to, I recommend not using it, as it is less stable because it is much more sensitive to non-linearity in the modeling. You also have to deal with the added complexity of ensuring you only use nested nodes to get any benefit.

As the question for what order1 and order2 should be:
There is no "correct" answer, but my recommendation depends upon what you are trying to do. Are you trying to see how well PCE spars against MCI, or are you trying to apply PCE on a problem with computational budget so high, that MCI isn't feasable?

**Comment by daxterss** [comment]
Thanks for your comments jonathf!

I want to use PCE for car design and optimisation. Initially, the shape is only defined with 3 variables. For my application, I want to use PCE because MCI will not be feasible... What is your recommendation to set "order1" and "order2"?

My initial thought was to define a baseline design, carry out a MCI and check what "order1" and "order2" should be by comparing statistical quantities (mean, std, pdf...). Then, use those values of order1 and order2 throughout the optimisation with UQ. Having said this, my problem is, a priori, non-linear which leads me to think that order1 and order2 can not be considered constant for different designs.... Your thoughts and view on this will be very much appreciated!

**Comment by jonathf** [comment]
Assuming you are using bound distribition (like Uniform), I'd go for a `clenshaw_curtis` sampling scheme. Use `growth=True` to ensure that the samples are nested between order. This way, the evaluations done at a lower order can be reused. (Remember to store things though.)

For techincal reasons `growth=True` implies that the number of quadrature points should be around `2^((N+1)*D)` (where N is order and D is dimensions) which is quite high. So I'd go for the following strategy:

* start with e.g. `order1=3`
* use the number of polynomial terms to determine the need number of samples: `needed_samples=2*len(polynomial_expansion)`
* Find smallest `order2` such that `len(weights) >= needed_samples`
* If results for `order1` and `order1-1` are about the same, you are done, otherwise jump to step 1 and bump `order1`.

In my experience smooth CFD without any discontinuities (in function or derivative), you will need order1 somewhere between 6 and 9. But that is just a guess. the real value will depend on the problem.

If this is too expensive, it is possible to experiment with increasing `cross_truncation` passed to `orth_ttr`. It reduces the number of polynomial terms at the expense of assuming lower complexity in the interaction between the parameters.
