### ISSUE TITLE
Quadrature Points Outside Support

### ISSUE THREAD

**Issue by Alexander-Hill1** [jonathf/chaospy#218]
Hi Jonathan,

I'm generating quadratures using rule 'gaussian' for a truncated one dimensional Pareto1 distribution, where I increase the order monotonically and look at the returned nodes. I find that the nodes fall within the expected support up to order 22, after which an increasing number of nodes begin to fall outside the support.

Here is my code, can you reproduce the error, and if so could you please suggest a fix?

```
from chaospy import (generate_quadrature, Uniform, Pareto1, trunk)
import numpy as np
import matplotlib.pyplot as plt

quadrature_rule = 'gaussian'

standard_input = Pareto1(loc=-1.99, scale=2, shape=1)
dist = trunk(standard_input, 10)

#dist.lower = 0.01, dist.upper = 10.

quad_orders = np.arange(5, 30, 1)

plt.figure()

for quad_order in quad_orders:
    nodes, weights = generate_quadrature(quad_order, dist, rule=quadrature_rule, growth = False, sparse = False)
    y_data = np.ones(len(nodes[0]))*quad_order
    plt.scatter(nodes[0], y_data)

plt.show()

```

**Comment by jonathf** [comment]
I'll suggest more than one.

1. today I have been working on increasing the accuracy of the quadrature function.
I've pushed the changes now to version 3.2.5.
Switching to it implies the integration scheme changes. Hopefully for the better.

2. Set the algorithm for generating recurrence coefficients by passing `recurrence_algorithm="..."` to the `generate_quadrature` function.
You can choose from "stieltjes" (default), "chebyshev", and "lanczos".

3. Set the accuracy for the approximation method by passing new integer value `accuracy=...` to `generate_quadrature`. (This only works on 3.2.5 because of a bug.)

I experimented with your particular problem, and looks like "lanczos" is a really good fit for your distribution.

**Comment by Alexander-Hill1** [comment]
Great stuff, "lanczos" indeed works really well.

Thanks!
