### ISSUE TITLE
chaospy.caller.call

### ISSUE THREAD

**Issue by rhaghi** [jonathf/chaospy#240]
Hi Jonathan,

Thanks again and again for this very useful package!
I have a question regarding `chaospy.caller.call` command. I used it before to evaluate regression output polynomials as a Monte Carlo simulator. It seems it is not part of the package anymore, am I right? Is there a substitute? I tried to use `chaospy,poly.call`, but the output is `numploy.ndpoly` instead of `numpy.ndarray`. Am I missing something?

**Comment by jonathf** [comment]
It is correct that the `call` function no longer is a part of the `chaospy` package. It is because the polynomial representation has been moved to [numpoly](github.com/jonathf/numpoly).

On a higher level, you don't need it anymore, as the polynomials themselves support substitution through the call signature. E.g.:
```python
polynomial(q0=2*q1-1, q1=q0*q1, ...)
```

However, the lower-level interface still exist, but in `numpoly`:
```
import numpoly
numpoly.call(...)
```
Note that I call it lower-level because not all functionality in `chaospy` is 1-to-1 with the same functionality in `numpoly`. E.g. `chaospy` assumes all variables are on the form `q0, q1, q2, ...`, while `numpoly` allows for any valide python variable name. So some care has to be taken when using the `numpoly` library directly with `chaospy`.

**Comment by jonathf** [comment]
Oh, I might be misunderstanding. If you are only referring to the output type, take a look at the docs for `help(numpoly.call)`. Depending on if the resulting output is constant or not, it will return `ndarray` or `ndpoly` depending on what is appropriate.

**Comment by rhaghi** [comment]
Thanks Jonathan!
I meant the output. I want to substitute all the variable `q0, q1, q2, ...` with numbers in my polynomial and have a number `ndarray` as the output. It seems it is not possible to feed an `ndarray` into `numpoly.call` and get a number. For example, let's say we have a polynomial with 10 variables, then:

`numpoly.call(polynomial,0,0,0,0,0,0,0,0,0,0)`

gives a number as the output. However:

`numpoly.call(polynomial,numpy.array([0,0,0,0,0,0,0,0,0,0]))`

gives 10 polynomials. Is it possible to have a number while feeding an array to `numpoly.call`?

**Comment by jonathf** [comment]
Something like this: `numpoly.call(polynomial, *numpy.array([0,0,0,0,0,0,0,0,0,0]))`?

**Comment by rhaghi** [comment]
Yes! Thanks a lot! It works! I didn't know about the star before `arg` :)

**Comment by jonathf** [comment]
Right. Good.

Note that you don't need the interface as it is also possible to do `polynomials(*array(...))`.

Closing.
