### ISSUE TITLE
Getting truncated distributions from sampling with MvNormal

### ISSUE THREAD

**Issue by tanweihou** [jonathf/chaospy#321]
**Problem**
I am trying to use `chaospy.MvNormal` to generate pseudo-random samples of a 2D Gaussian distribution with given covariance matrix. However, the resulted distribution truncates at certain values.

Did I make some mistakes in the following code ?
Thank you.

**Code**
```
covmat = np.array([[0.01427607, 0.04097744],
       [0.04097744, 0.12098941]])

distribution = cp.MvNormal([0, 0], sigma=covmat)

sample_chaospy = distribution.sample(2000)

rv = multivariate_normal([0, 0], cov=covmat)

sample_scipy = rv.rvs(size=2000)
```

**Plot**
![plot](https://user-images.githubusercontent.com/15125658/108798528-9788ea80-7553-11eb-9c62-bfd76f49e0b5.jpg)

**Comment by jonathf** [comment]
Chaospy needs to have finite bounds on all its distributions to work. However, those bounds should be wide enough that it covers the domain in question well enough that the user don't notice it. Here you see what happens when the bounds are too narrow.
So that shouldn't happen, so this is a bug.

I think I've found what is causing it and applied a patch. Try again with chaospy version 4.2.4 and let me know if that solves the problem.

**Comment by tanweihou** [comment]
Thanks for the help.
It works for me using Halton, random, or Sobol sampling rules.
However, it does not work if I choose to sample with grid, please check the plot below.

![plot](https://user-images.githubusercontent.com/15125658/108867354-ba021e80-75ba-11eb-8877-bbc58ca3baf8.jpg)

**Comment by jonathf** [comment]
I think your plot is lying a bit. Grid misbehaves a little, specially at the edges, as it is not (pseudo-)random.
Try instead `matplotlib.pyplot.hist2d(*samples, bins=100)` and you will see how the samples distributes in space.

**Comment by tanweihou** [comment]
Thanks a lot ! You are correct, indeed `pyplot.scatter` misbehaves for samples generated from grid.
I shall proceed to close this issue.
