### ISSUE TITLE
Stochastic dependent variables

### ISSUE THREAD

**Issue by John3221** [jonathf/chaospy#338]
Hi @jonathf,

Thanks for this software, it's been very useful to my research.

I'm trying to implement a system with a stochastic variable that is dependent on a underlying deterministic variable - I'd be very grateful if you could point me in the right direction.

For example if I have some normally distributed random variable w, then I would like the value of this variable to be in someway inversely proportional to another deterministic variable, 0<=x<=1. That is to say, w should be defined in such a way that if x is small then the probability of w being large is greater, and if x is large then w tends to take on smaller values for example.

**Comment by jonathf** [comment]
Thank you for you kind words. I am glad you like it.

What you are describing sounds like you could do something as simple as `chaospy.Normal(-x, 0.01)`, but I imagine you are hinting at something more fancy. But I need to know more about your problem before I can give more specific advice on your problem.

**Comment by John3221** [comment]
Thanks for your quick response. 

I'll try to describe the high-level problem to give you a better idea. Apologies in advance for the long post, I am happy to have this conversation via email or another platform if that is more appropriate. 

I have a 2D domain with a deterministic variable, 0<= x <= 10, that varies in space within this domain. I use the values of x in this domain to compute an integral, which gives me a quantity of interest, lets say W (so W = f(x)). Changing x anywhere in the domain impacts W in a non-linear fashion. I have been able to introduce uncertainty to this system, by adding a variable, v, defined using a normal distribution. This variable modifies x everywhere in the domain (lets call this modified variable x_ = f(x,v)) and this can be used to compute W_ (W_ = f(x_)). As W_ is no longer deterministic, I use random field modelling to model a series of spatial distribution of v within the domain and then use PCE to compute the low order statistics of W_. 

I am now hoping to modify v such that it is dependent on x. So whereas before v = f(P, X), where P is the underlying probability function, and X are the spatial dimensions, I am now hoping to model v = f(P,X,x), that is to say that v is dependent on the value of x. So for example, if x is small in one location then the probability that v is large at that location should be greater and vice versa. I think your suggestion of using `chaospy.Normal(-x, 0.01)` is valid, but I don't know how this would be used within a PCE setting for example. 

Do you think something like this is feasible?

**Comment by jonathf** [comment]
I feel you are still a bit abstract, so I appologies if I missunderstood anything.

I think you need to clean up your name space. Instead of
`f(x), f(x, v), f(x_), f(P, X), f(P.X,x)`, I think you should just stick to one
function: `f(v)`. We define it as having an stochastic input, but internally in
your implementation will assume to be an float point scalar value.

The function will be assumed to have an multivariate output assumed to be on a mesh.
You note that you have a 2D domain and that x varies, I would then assume that
`f(v)` outputs a 3-order tensor. 2 for your physical domain, and 1 for varying
x. The varying x, btw, you will need to mesh up. E.g.
`x = numpy.linspace(0, 10, 100)`.

Now inside `f` you will need to implement all the features you need. E.g.
if you want `v` to be dependent on x, you can add that:
```python
v = v-x
```

If the `x` is assumed constant as you solve the integral, you might want to
loop over the `x`:

```python
out = numpy.array([solve_integral(x_, v) for x_ in x])
```
Here `solve_integral` will return a 2D mesh of values.

Adding probability functions (I'm assuming either pdf or cdf) is also possible, but
in my experience, it is rarely what one wants.

If have reached the point that `f(v)` works as a deterministic function, then
you are ready to apply `chaospy` to analyse the uncertainty.

I hope this helps.

**Comment by John3221** [comment]
Hi again,

Yes, apologies for being so abstract, I tried to generalise my problem in an attempt to make it easier to understand but I may have done the opposite. 

I think what you have said makes perfect sense and I already have the function `f(v)` that you have described. I think I was overcomplicating it too much. Thank you very much for your time and help!
