### ISSUE TITLE
Usage of chaospy.QoI_Dist()

### ISSUE THREAD

**Issue by ahenkes1** [jonathf/chaospy#339]
Hi @jonathf ,

I am unsure about the correct usage of `chaospy.QoI_Dist()`. Let's say I have an independent multivariate input distribution and a multidimensional function. I propagate the input distribution through the model via pseudospectral gPCE. I get an approximation of the function distribution in the form of a polynomial. So far so good. Now I want to take a look at the corresponding PDFs/CDFs of each output of my function by KDE using `chaospy.QoI_Dist()`. A sample code could look like this (**chaospy version: 4.2.7 via pip**):

```
import chaospy as chp
import numpy as np


dist_joint = chp.J(chp.Normal(mu=1000, sigma=100),
                   chp.Normal(mu=0.2, sigma=0.02))

dist_proxy = chp.Iid(chp.Normal(mu=0, sigma=1), 2)

poly = chp.orth_ttr(order=5, dist=dist_proxy)

nodes_proxy, weights_proxy = chp.generate_quadrature(order=5,
                                                     dist=dist_proxy,
                                                     rule='gaussian')

nodes_joint = dist_joint.inv(dist_proxy.fwd(nodes_proxy))

weights_joint = weights_proxy * dist_joint.pdf(nodes_joint) \
                / dist_proxy.pdf(nodes_proxy)

solves = np.zeros(shape=(nodes_joint[0].size, 3))
counter = 0
for ab in nodes_joint.T:
    solves[counter, :] = [ab[0], ab[1], ab[0] * ab[1]]
    counter += 1

approx = chp.fit_quadrature(orth=poly,
                            nodes=nodes_proxy,
                            weights=weights_joint,
                            solves=solves)
```

Now I want to construct the KDE. I figured out two possible ways, and I am unsure, which one is correct.

1. Constructing one KDE using `approx` directly:

`dist_qoi = chp.QoI_Dist(poly=approx, dist=chp.Iid(chp.Normal(mu=0, sigma=1), 3))`

This will result in a 3-dim distribution, where the H-matrix of the KDE is diagonal and I get stochastic dependency. Therefore `pdf = dist_qoi[0].pdf(x)` is possible whereas `pdf = dist_qoi[1].pdf(x)` for some `x` will result in the following error:
`chaospy.StochasticallyDependentError: ItemDistribution(1, GaussianKDE()) has dangling dependencies`.

2. Constructing separate KDE for each dimension of `approx`:

```
dist_qoi_1 = chp.QoI_Dist(poly=approx[0], dist=chp.Iid(chp.Normal(mu=0, sigma=1), 3))
dist_qoi_2 = chp.QoI_Dist(poly=approx[1], dist=chp.Iid(chp.Normal(mu=0, sigma=1), 3))
```

Here it is possible to obtain the corresponding PDFs/CDfs for each distribution, but the resulting graphs depend on the sampling distribution of `chp.QoI_Dist`, which should not be the case, if I am not mistaken. If this second approach is correct, do I need some transformation to obtain the "correct" distributions, i.e. which are independent of the kernel?

**Comment by jonathf** [comment]
When a multivariate distribution is dependent, it means that the pdf and cdf can only be define together. If you want to define only one, than you have to "marginalize", which implies that you are loosing the dependency relationship.

In chaospy, variables usually do not marginalize, with exception of the first variable. This is because chaospy uses a density compostion: `p(x,y,z) = p(x) p(y|x) p(z|x,y)`. This is what you see in (1). But this is an implementation detail, and extracting out `p(x)` still means you are loosing dependency information if you use it independent of the other variables.

Your approximation `approx` is a 2 variable input, 3 variable output. Your input is stochstically independent, but the output is dependent. (Note though that the picture is a bit complex since you live in the world where `approx[0]` is in fact independent of `approx[1]`, but that is not generally true.)

If you want to construct a model that incorporates the dependencies between the dimensions, approach (1) is the way to go. But indexing the distribution, like you are doing, will not be possible, as chaospy does not marginalize (except for dim 1). You will have to do pdf jointly `p(x, y, z)`. And cdf is not defined.

If you want to ignore the dependencies (which in paractice exists between `approx[2]` and the others), approach (2) is the correct way to marginalize them. It discards the dependency information in favor of allowing for marinal pdfs `p(x), p(y), p(z)` and cdfs `F(x), F(y), F(z)`.

Sidenote, your implementation of QoI should use the flag `dist=dist_proxy`. But as you are using the same distribution (though at one higher dimension), the result is the same.

Hope this makes sense.

**Comment by ahenkes1** [comment]
Thank you very much for your extensive answer, it clarified a lot for me!
