### ISSUE TITLE
Rationale behind the bounds for normal distribution

### ISSUE THREAD

**Issue by damar-wicaksono** [jonathf/chaospy#392]
Hello,

I notice that the lower and upper bounds for the normal distribution in Chaospy were given values; for a long time they were, I think, -7.5 and 7.5.
In the recent commits, they were changed to -8.22 and 8.22.

I was looking for the reasoning behind these numbers and their recent changes in the docs and in the commit messages and couldn't find one. Perhaps it's obvious (numerics? practicalities?) but, unfortunately, not to me.  Could you please perhaps give an explanation?

Thanks a lot for your help!

**Comment by jonathf** [comment]
Yeah, you are right. This is not explained well enough.

The bounds are needed for practical implementation. It is a tradoff between accuracy and computational cost.
The 7.5 value is arbitrary. Typically not important, but for some application the higher accuracy is important.

The new values xlo, xhi were selected so that the error in the term `1 - int_xlo^xhi p(x) dx` is bellow 1e-15, which about the PCE accuracy you will plateu at on the x86_64 platform.

**Comment by damar-wicaksono** [comment]
Thanks a lot for the explanation!
Now I think it makes much more sense.

PS: Feel free to close this Issue.
