### ISSUE TITLE
Chaospy variable in an exponential function

### ISSUE THREAD

**Issue by hamzabuw** [jonathf/chaospy#394]
Hi,

I am currently working on applying **Intrusive PCE** to **Arrhenius Equation** working on fire safety problems at Uni Wuppertal, Germany.

While performing exponential of the chaospy variable 'E' here:
![ksnip_20221004-182526](https://user-images.githubusercontent.com/97860562/193874025-54923d73-166a-4199-8cc7-1e5df176749a.png)

I get the following error:
![ksnip_20221004-182619](https://user-images.githubusercontent.com/97860562/193873809-6d647813-3d79-42ca-ad3c-4bc952031e09.png)

As I understand the numpoly array function does not allow using of exponential. Would that be implemented in a future version or can you give me some guidance in that regard?

Can I perhaps myself simply alter the add.py function for example to create an exponential function to fix this issue?

![image](https://user-images.githubusercontent.com/97860562/193874569-e656ce73-c948-40e6-b711-f40f49aa5ccf.png)

Thank you in anticipation.

**Comment by jonathf** [comment]
Doing the e^poly isn't really possible, as the output isn't a polynomial. You see all the operators in numpoly assumes that both input and output can be coerced to a polynomial type.

Since you are doing intrusive PCE I guess you have a couple of options.

1. Replace `exponential_polynomial` with a Tailor expansion.
Make the expansion significantly longer then the PCE expansion, and that should be fine.

2. Reformulate the Arrhenius equation by taking the logarithm on both sides and model the rate constant as log-rate.
If the rate is an uncertain input parameter, you could perhaps try to figure out what the distribution of the log-rate should be first.

I think (2) is your best option, but that approach will likely require more work.
Let me know how it works out.

**Comment by hamzabuw** [comment]
Thank you for the detailed response. Sorry I needed some time to implement and test your recommendations.

  1. I managed to get the method one working which I initially couldn't due to largely negative values in the exponential which run into computer precision issue unless we center the expansion close to the mean value:

  ![image](https://user-images.githubusercontent.com/97860562/202544240-541c5342-3398-4b27-a5a4-cfd0b55425b8.png)
  However, this does not function for PC order above 2.

  2. I tried the option 2 as well but the issue is that I need the moments (for comparison) of mass loss rate which is computed as differential of the rate constant.

  3. There is another option is integration approach mentioned by [Bert J. Debusschere ](https://doi.org/10.1137/S1064827503427741). I haven't worked on it yet but will keep you posted.

Secondly, pertinent to our discussion and Bert J. Debusschere's papers, I want to understand the difference of his notation with chaospy. Chaospy denotes the uncertain variable _β_ as e.g. from the [example case](https://chaospy.readthedocs.io/en/master/user_guide/main_usage/intrusive_galerkin.html):

![image](https://user-images.githubusercontent.com/97860562/202545759-6d9096cb-e651-40a3-877c-2f559c285417.png)

Whereas, Debusschere actually performs the PC expansion of the input variables as well. As from his [paper](https://link.springer.com/referenceworkentry/10.1007/978-3-319-12385-1_19):
![image](https://user-images.githubusercontent.com/97860562/202555027-d56eaec9-ed8a-4ad6-9ab4-89cccfc38e46.png)
Where b is the uncertain variable and the rest are the output variables.

Can you kindly also explain why is that?

**Comment by jonathf** [comment]
Seems like a hard issue to tackle. I can help with the code, but you seem to need help with the problem first and foremost, which I think I am of limited help as my time is a bit limited these days.

As for notations, the difference in notations is minimal here. $\Phi$ and $\Psi$ are the same. $\xi$ is usually implicit in my code, but in the example it is $\xi = (\alpha, \beta)$.
Otherwise it is the same.

Hope this helps.

**Comment by hamzabuw** [comment]
I will try to work on it on my own first and keep you posted. Thanks.

Actually regarding the notation, my question is that why is _β_  not expressed in PCE as **b** is in the Debusschere's case? Is it be because _β_ in chaospy already constitutes the PCE expansion implicitly when we say `β = chaospy.variable(1)` ?

Sorry if my basics are still weak.

**Comment by jonathf** [comment]
The variables $\beta$ and b are not the same.

b is a non-trivial random variable that needs its own expansion to express correctly. That is why Debusschere expresses it as an expansion. $\beta$ is a simple variable with a trivial distribution that is easy to do analytics on. You could give it an expansion, but you would only end up with $\beta = \beta$ in the end.

Try to think of you random variables in two groups: The simple ones that you can do analysis on, and he complicated ones that you need to approximation with the simple ones. In this scenario $\beta$ is of the former and `b` is of the latter.

**Comment by hamzabuw** [comment]
Thank you for the explanation.  
Can you recommend some source material which explains about how to decide if a variable is trivial or not?

**Comment by hamzabuw** [comment]
I will go through these. Thank you for the support.
