### ISSUE TITLE
Uniform distribution with lower and upper band functions

### ISSUE THREAD

**Issue by rhaghi** [jonathf/chaospy#410]
Hi Jonathan,

Thanks a lot for the great library.
I am trying to define a uniform distribution while the upper and lower band are functions of another uniform distribution. This is my implementation. 
```
a_LB = 0.15
a_UB = 0.22
D = 126
R = D/2
U_max = 25
z = 90

U = cp.Uniform(lower = 3, upper=25)

def alpha_lb(U):
    if (a_LB-0.23*(U_max/U)*(1-(0.4*np.log10(R/z))**2)) < -0.3:
        lb = -0.3
    else:
        lb = a_LB-0.23*(U_max/U)*(1-(0.4*np.log10(R/z))**2) 
    return lb

alpha_ub = a_UB + 0.4*(R/z)*(U_max/U)

alpha = cp.Uniform( lower = alpha_lb, upper=alpha_ub)

```

This doesn't work as `U` is a distribution, not an array. How do you think I can implement this? 

Thanks!

**Comment by jonathf** [comment]
The distribution that you propose is not possible in chaospy, unfortunatly.

There are two issues.

First, your `alpha` distribution is described as a conditional distribution dependent on `U`. In chaospy distributionhs like that are not allowed to operate alone. Instead a joint distribution can be created as `cp.J(U, alpha)`, which could work. But the marginal of `alpha` is outside the scope of chaospy.

Second, the real issue is that your distribution definitions contains an inequality compare. In the early days of chaospy I experimented with support with support for this. Unfortunalty the implementation  was buggy, and I ended up having to remove it. In other words, it is theoretically possible to do something like this, but right now there isn't any machinery for it. One day if I have time again, I might give it another go, but until then, you are out of luck.

**Comment by rhaghi** [comment]
Thanks for your reply. I found a way around it! This is my code:

```
import chaospy as cp
import numpy as np


nos = 2**12
U = cp.Uniform(lower = 3, upper=25)

a_LB = 0.15
a_UB = 0.22
D = 126
R = D/2
U_max = 25
z = 90


alpha_lb = a_LB-0.23*(U_max/U)*(1-(0.4*np.log10(R/z))**2)
alpha_ub = a_UB + 0.4*(R/z)*(U_max/U)



alpha = cp.Uniform(lower =alpha_lb , upper=alpha_ub)


joint_dist1 = cp.J(U,alpha)
joint_dist1_T = cp.Trunc(joint_dist1,lower=-0.3,upper=30)

samp1 = cp.generate_samples(nos, joint_dist1_T,rule='S')
```

My only question is about the `cp.Trunc` upper limit. If I set it at `None` it truncates the joint distribution at 0.5 for the upper limit. That's why I set it at the arbitrary number of 30. Why is that?

Thanks a lot for your time and help.

**Comment by jonathf** [comment]
The trunk distribution is limited to independent variables. It is a limitation in the implementation.

Your best bet from here, is to sample from this distribution and remove samples that "overshoots" the interval (-0.3, 30).
