### ISSUE TITLE
Test local build - 1 Test failed (chaospy.poly.collection.core.cutoff)

### ISSUE THREAD

**Issue by marion2007** [jonathf/chaospy#60]
Hello Jonathan, 
I have installed chaospy and run the test as recommend. I get 113 passed tests but one failed test. I assume this is not the output that I'm supposed to get. Do you have any suggestions what I could try or where I could find more info? 
Thank you very much for your help! 
Marion 

================================== FAILURES ===================================
________________ [doctest] chaospy.poly.collection.core.cutoff ________________
095                 Defaults to 0.
096         high (int) : The upper threshold for the cutoff range.
097
098     Returns:
099         (Poly) : The same as `P`, except that all terms that have a order not
100                 within the bound `low<=order<high` are removed.
101
102     Examples:
103         >>> poly = cp.prange(4, 1) + cp.prange(4, 2)[::-1]
104         >>> print(poly)
Expected:
    [q1^3+1, q1^2+q0, q0^2+q1, q0^3+1]
Got:
    [q1^3+1, q0+q1^2, q0^2+q1, q0^3+1]

D:\Python\chaospy\chaospy\src\chaospy\poly\collection\core.py:104: DocTestFailure
==================== 1 failed, 113 passed in 9.14 seconds =====================

**Comment by jonathf** [comment]
Hey!

This does not matter very much.

What you are seeing here is output that depends on the ordering of the content of a dict. I am using Python 3.6 where dicts are ordered, so my tests all pass. But for any version of Python pre-3.6, dictionaries are randomized so that the ordering might differ.

When I get around to it, I will try to fix this. Obviously it would be greate that the tests pass for all versions of Python, not just CPython 3.6.

**Comment by marion2007** [comment]
Hey,

thank you very much for your help! I saw that the ordering for the second term different to the expected output but I wasn't sure if that was indicating something more. 

Thank you very much for providing and maintaining chaospy! 

-Marion

Am 14. Oktober 2017 14:56:44 MESZ schrieb Jonathan Feinberg <notifications@github.com>:
