### ISSUE TITLE
Issue obtaining orthogonal polynomials for multivariate function

### ISSUE THREAD

**Issue by flapingwings** [jonathf/chaospy#75]
Hi Jonathan,

I receive the following  error message: 

>  MemoryError: Too large sets

when I run the following script:
```
distribution = cp.J(cp.Normal(-1,1), cp.Weibull(1.1,90,-180), cp.Uniform(0,10), cp.Uniform(0,10))
orths, norms = cp.orth_ttr(2, distribution, normed=True, retall=True, cross_truncation=1.5)

```
I figure that it is the Weibull distribution that's causing the error. 
The above script is only a sample, for the problem at my hand I have many input variables having Weibull distribution.
It would be very helpful if you can suggest a work around for the problem.

Thank you.
Kind Regards,
Rahul

**Comment by jonathf** [comment]
This problem is somewhat challenging.

The default behavior of `chaospy` for creating orthogonal polynomial coefficients is to use analytically derived so-called "three terms recurrence coefficients". These exists for lots of distributions, and in many cases a general expression can be used, and everything is fast and easy. For probability distributions that does not have analytically derived coefficients available, an approximation method has to be used instead, which in the case of `chaospy` is Golub-Welsch. The transition from analytical to approximation is seemless, and is triggered any time a uncomputable quantity is included. The Weibull distribution is such a distribution, which means that anytime it is included, Golub-Welsch method is triggered.

Golub-Welsch contains parts that require numerical integration. When that happens the `orth_ttr` function  passes extra parameters to a function called `generate_quadrature` for the parts where numerical integration is needed. One parameter to notice is `accuracy`, which sets the number of evaluation nodes used during integration. It defaults to 100, which in your case is high enough to causes MemoryError.

So the solution is to play around with `accuracy` to find the highest value that still allows you to compute the quantity of interest. A quick test on my machine, and I got away with using 50, but it might differ on your system.

**Comment by jonathf** [comment]
Okay, I've just pushed an update to the branch `development` that spilts the problem up doing each dimension separately. This means that that the code no longer integrates of the full probability space, but instead does one and one dimension, using analytical TTRs when available.

I haven't had time to test it much, so let me know if it solves your problem.

**Comment by flapingwings** [comment]
First of all, thanks for explaining the problem in detail.
I did a quick testing with the updated _stieltjes.py_ file and found that the issue is solved.

Thank you.
