### ISSUE TITLE
Bug with truncation on a dependent distribution

### ISSUE THREAD

**Issue by RRiva** [jonathf/chaospy#79]
Hi, I would like to truncate a dependent distribution, but the following code doesn't work.

```
import numpy as np
import chaospy as cp
import matplotlib.pyplot as plt

dist_1 = cp.Uniform(1, 2)
dist_2 = cp.trunk(cp.Normal(5.0,dist_1), 6.0)

dist_J = cp.J(dist_1, dist_2)
sample_J = dist_J.sample(int(1e6))

fig, ax = plt.subplots()
plt.hist(sample_J[0,:], density=True, bins=4, ec='black')
plt.hist(sample_J[1,:], density=True, bins=40, ec='black', alpha=0.7)
plt.show()
```

**Comment by jonathf** [comment]
I have looked into the usecase, and the bug traces into the backend without any obvious source to why this is happening. I doubt I will be able to fix this bug in the short term.

As a workaround, try the following:
* Switch to branch `dist_clean`.
* Switch out the definition of `dist_2` with:
  ```
  dist_2 = cp.TruncNormal(lower=-100, upper=6, mu=5, sigma=dist_1)
  ```

Hope this suffice to solve your problem.

**Comment by jonathf** [comment]
Looking a little closer, I am realizing that the solution I am proposing is very satisfactory, and a real solution is first and foremost a philosophical one.

The core problem is what the relationship a truncated distribution has with the whole distribution. E.g.
```
u1 = cp.Uniform()
u2 = cp.Trunk(u1, 0.5)
uu = cp.J(u1, u2)
```
This has to be split into components, either (A) `u1, u2|u1` or (B) `u2, u1|u2`.

In case A, `u2|u1=0.1` is unproblematic and results in `u2=0.1` as well. the problem arises, if we have a sample `u2|u1=0.9`. Since `u2=u1|u1<0.5` we get `u1|u1=0.9,u1<0.5` which is a paradox.

In case B, `u1|u2` is unproblematic irrespectively, but confines `u1` to `<0.5`.

As far as I reason, the correct way to solve this problem is to assume that `u1==u2`.

For your more complicated case, the solution is not as simple, but I think the same principle applies. Let me know.

**Comment by RRiva** [comment]
Thanks for your work. I don't think that the two distributions should be equal to each other. For example

```
dist_1 = cp.Normal(0.0, 0.5)

dist_2 = cp.Uniform(0.0, 5.0)                              # Case A
dist_2 = cp.Uniform(dist_1, 5.0)                           # Case B
dist_2 = cp.Uniform(cp.trunk(0.0,dist_1), 5.0)             # Alternative 1
dist_2 = cp.Uniform(cp.Uniform(0.0,dist_1), 5.0)           # Alternative 2

dist_J = cp.J(dist_1, dist_2)
```

In this case I just want to build a uniform distribution, for which the lower boundary is the maximum between two functions, one of which is a distribution. A and B are the extreme cases. A is the desired result before 0, while B is the desired one after 0. The alternatives 1 and 2 should provide the same result, and both don't work. I really don't see why it is problematic to assign an arbitrary distribution as a boundary.

**Comment by jonathf** [comment]
No, alternatives 1 and 2 are not equivalent. The number of underlying random variables has to match the number of variables provided to the joint operator.

In alternative 1 you define 2 underlying random variables for you joint distribution. This is because truncation is an univariate operator and not a independent variable. The problem is then as I described above about internal paradoxes.

In alternative 2 you define 3 random variables; one normal and two uniform, but your joint only receives the definition for 2. To complete that example, you must introducing the third variable.

For example:
```
dist_1 = cp.Normal(0.0, 0.5)
tmp = cp.Uniform(0, dist_1)
dist_2 = cp.Uniform(tmp, 5.0)
dist_J = cp.J(dist_1, dist_2, tmp)
```
Depending on your usecase you can now just ignore whatever `tmp` produces. But it must be included in the definition for the Rosenblatt algorithm to be able to do its thing.

Having said that, I might be able to hide this logic behind the scene if the only component required from the distribution is random number generation and statistical moments.

**Comment by RRiva** [comment]
Thanks for the clarification. That would be nice, but I don't consider it particularly important. Instead, I think it's better to fix/avoid the paradoxes.

**Comment by jonathf** [comment]
I am leaving this issue open for now because the error caused is very non-descriptive.
I am working on a bigger update and I'll add a more descriptive error there.

**Comment by RRiva** [comment]
Thanks, I'm looking forward to it!
