### ISSUE TITLE
example for probabilistic collation method.

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [jonathf/chaospy#88]
Hi you,
Now, I am studying about Probabilistic collation method. Do you have any example or the manual about the method. Please introduce to me. I really need it for my research. 
Thank you very much

**Comment by jonathf** [comment]
Depends on what you mean by probabilistic collocation method. If you mean point collocation method, then perhaps this would help?
http://chaospy.readthedocs.io/en/master/tutorial.html#point-collocation-method

**Comment by nguyenhoaiThanhbk2811** [comment]
The probabilistic collocation method (PCM)(Tatang, 1994) is a tool designed to enable uncertainty analysis of computationally expensive models at a very low computational cost. I don't know the point collocation method in the chaospy is this PCM or not. 

I am following the PCM of Tantang,1994 and the method was used in this paper.
http://highorder.berkeley.edu/proceedings/aiaa-annual-2007/paper0914.pdf

Could you give me your recommend.

Thank you

HoaiThanh

**Comment by jonathf** [comment]
Right. It has been awhile since I seen this paper. I was wondering if that was what you really meant.

As far as I can see, most of the implemenation can be reduced down to creating Lagrange polynomials and optimal Gaussian-Hermite quadrature points.

To create the Lagrange polynomials you have the function `chaospy.lagrange_polynomial`. It is used as follows in one and two dimensions:
```
        >>> print(chaospy.around(lagrange_polynomial([-10, 10]), 4))
        [-0.05q0+0.5, 0.05q0+0.5]
        >>> print(chaospy.around(lagrange_polynomial([-1, 0, 1]), 4))
        [0.5q0^2-0.5q0, -q0^2+1.0, 0.5q0^2+0.5q0]
        >>> poly = lagrange_polynomial([[1, 0, 1], [0, 1, 2]])
        >>> print(chaospy.around(poly, 4))
        [0.5q0-0.5q1+0.5, -q0+1.0, 0.5q0+0.5q1-0.5]
        >>> print(numpy.around(poly([1, 0, 1], [0, 1, 2]), 4))
        [[1. 0. 0.]
         [0. 1. 0.]
         [0. 0. 1.]]
```

To create the absicias and weights from Gaussian-Hermite, you can do as follows:
```
    >>> distribution = chaospy.Iid(chaospy.Normal(0, 1), dimensions)
    >>>> absicias, weights = chaospy.generate_quadrature(order, distribution, rule="G")
```

From there you will have to get your hands dirty with transformations and solving of the Galerkin projection problem. I haven't implemented this algorithm before, so I don't know how complicated it is, but I believe you have the tools you need here. Let me know if there is a specific operation that you are missing and need help with.
