### ISSUE TITLE
Wrong assessments regarding OpenTURNS

### ISSUE THREAD

**Issue by regislebrun** [jonathf/chaospy#96]
Hi,
I am the main developer of the OpenTURNS platform and I noted many **wrong assessments** in the description of OpenTURNS in your theory guide:
- The Rosenblatt transformation is available for nearly 10 years (see [here](http://trac.openturns.org/browser/tags/openturns-0.12.2/lib/src/Uncertainty/Algorithm/IsoProbabilisticTransformation/Rosenblatt))
- The bootstrap resampling method is available for more than 8 years (see [here](http://trac.openturns.org/browser/tags/openturns-0.13.2/lib/src/Uncertainty/Algorithm/Experiments))
- From its inception, OT has been designed to take into account dependence through copulas. In addition to the most standard copulas, it offers several mechanisms to combine or to define copulas (ComposedCopula, OrdinalSumCopula, SklarCopula, EmpiricalBernsteinCopula, ExtremeValueCopula, Mixture), most of them being available long before you wrote your guide. Note that SkarCopula allows to define a copula from any continuous joint distribution (eg. from multivariate mixtures of distributions). It is even possible to define your own copula in Python, thanks to the OpenTURNSPythonDistribution python class.
- You wrongly assert that it is not possible to define a custom distribution in OT. It is the exact purpose of the OpenTURNSPythonDistribution python class, a 5 years old feature (see [here](http://trac.openturns.org/browser/tags/openturns-1.1/python/src)). The minimal information needed is the definition of the joint CDF and the range of the (potentially multivariate) distribution, same as in chaospy.
- It is of course possible to create a multivariate distribution from a set of univariate distributions and a copula in OT since the very first version of OT more than 11 years ago, see ComposedDistribution  [here]( http://trac.openturns.org/browser/tags/openturns-0.9.0/src/Uncertainty/Distribution), but many more options are available (Mixture, ConditionalDistribution, BayesDistribution to name a few)
- Variance reduction sampling methods are available in OT since more than 11 years, and DirectionalSampling, LHS (with randomized version), ImportanceSampling, QuasiMonteCarlo (with randomized version) were available at the time you started chaospy.
- Two orthonormalization algorithms were available in OT to compute 3 terms relation coefficients at the time you started chaospy, see GramSchmidtAlgorithm and ChebychevAlgorithm, the first one being the modified version of the algorithm to improve its stability and the second one being based on modified moments. An adaptive version of the Stieltjes algorithm has been introduced at the end of 2015, allowing to build the 3 terms relation for orthonormal polynomials associated to any continuous or discrete univariate distribution (assuming they have finite moments of any order)
- The UnivariatePolynomial class implements the full algebra of 1D polynomials as well as many other features for nearly 10 years
- Spectral projection is available for more than 9 years using the IntegrationStrategy class
- The collocation method (LeastSquaresStrategy) has always been available with all the sampling schemes for more than 10 years. There were 7 of them not counting variations (and not only 4) at the time you started chaospy
This report covers only the sections 1.1 and 1.2 of your guide. There are probably many more wrong assertions I will report soon.
You may have a look [here](https://tel.archives-ouvertes.fr/tel-00913510) to get some additional insights on isoprobabilistic transformation (title in French but content in English). 
Regards
Régis LEBRUN

**Comment by jonathf** [comment]
Dear Dr Lebrun

What you are pointing out is absolutely correct and there is little excuse for what I have done. I have removed the guide right away. Thank you for pointing it out. I am embarrassed that I let this happen, and I am very sorry.

The theory guide you found is quite obsolete written quite early during my PhD in 2011-2012 I think and was meant as a working document that would one day end up being the theory guide for chaospy. Along the way, I abandoned the original document started on a new theory guide which is now located in the `doc/` folder and is also currently being hosted on http://chaospy.readthedocs.io/
The old document, which contains lots of obsolete and incorrect assertions as you noted was just kept around in the `tutorial/` folder in hopes that I one day would get around to "updating" it and making it current. It was not actually meant for public view. But the day never came and it has just been lying there every since. And looking at it now I realize now that obviously some would be clicking `tutorial/theoryguide.pdf` as a quite intuitive thing to do to learn about the tool. This was quite foolish of me.

As a developer of a toolbox with overlapping functionalities, I can imagine this document seems deliberate, hostile and/or slandering. I hope that you can see that this is not my intent and that you and your group can accept my sincerest apology.

Lastly, thank you for taking the time outlining the feature capabilities of OpenTurn. I was aware of some of them, but not all. Having a full overview over what everyone is doing in the same space as you is often difficult, so overviews like these are quite helpful. I will take the time to explore some of these features in your platform for myself.

Regards
Jonathan Feinberg

**Comment by regislebrun** [comment]
Let's say that it is over. Things have been published and it is by this way that I heard about your toolbox. As for many open source initiatives, a negative feedback can hurt a lot, hopefully it has not been the case for OpenTURNS, which has a strong user support.
Now it is time to think about positive things. Would you be interested in starting a kind of collaboration? A way to do that could be to allow your users to benefit from the OT distributions in chaospy, or the other way for OT users. I don't know if it would lead to some benefit for them, but it can't hurt ;-)!
Régis

**Comment by jonathf** [comment]
Thank you.

That sounds like a very interesting idea. I definitely open to the idea of having some kind of comparability layer where that makes sense.

Please feel free to send me an e-mail to the address jonathan [at] feinberg.no and we can continue the conversation from there.
